// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_IhauUgs_acZH20FPOt_vvJA0CP5eASs',
    appId: '1:708792048561:web:6e09df801e5d3de21d7b90',
    messagingSenderId: '708792048561',
    projectId: 'desapego-75120',
    authDomain: 'desapego-75120.firebaseapp.com',
    storageBucket: 'desapego-75120.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBom9hGNG2qrn98z3JrhuaF-a-YWWOgNzI',
    appId: '1:708792048561:android:ed90482eca3501b81d7b90',
    messagingSenderId: '708792048561',
    projectId: 'desapego-75120',
    storageBucket: 'desapego-75120.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_IhauUgs_acZH20FPOt_vvJA0CP5eASs',
    appId: '1:708792048561:web:675a1be9005c25d91d7b90',
    messagingSenderId: '708792048561',
    projectId: 'desapego-75120',
    authDomain: 'desapego-75120.firebaseapp.com',
    storageBucket: 'desapego-75120.firebasestorage.app',
  );
}
